version: "3"
services:
  clickhouse:
    image: "yandex/clickhouse-server"
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    ports:
      - "9999:9000" # native interface
      - "8888:8123" # http interface
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8123/"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./users.xml:/etc/clickhouse-server/users.xml
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLICKHOUSE_PASSWORD
    ports:
      # UI
      - "4040:4040"
    volumes:
      - ./data:/app/data
    depends_on:
      - clickhouse
    links:
      - clickhouse
    restart: on-failure
  grafana:
    # TODO: use chproxy to cache response, rate limit requests
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "vertamedia-clickhouse-datasource"
      GF_SECURITY_ADMIN_USER: "guess"
      GF_SECURITY_ADMIN_PASSWORD: "youneverknow"
