version: "3"
services:
  clickhouse:
    image: "yandex/clickhouse-server"
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
    ports:
      - "9999:9000" # native interface
      - "8888:8123" # http interface
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 4G
        reservations:
          cpus: "2"
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8123/"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./users.xml:/etc/clickhouse-server/users.xml
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLICKHOUSE_PASSWORD
      - ITEMS_DIR=data/items
      - METADATA_DIR=data/metadata
    ports:
      # UI
      - "4040:4040"
    deploy:
      resources:
        limits:
          cpus: "16"
          memory: 8G
        reservations:
          cpus: "2"
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - ./data:/app/data
    depends_on:
      - clickhouse
    links:
      - clickhouse
  grafana:
    # TODO: use chproxy to cache response, rate limit requests
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "vertamedia-clickhouse-datasource"
      GF_SECURITY_ADMIN_USER: "guess"
      GF_SECURITY_ADMIN_PASSWORD: "youneverknow"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 500M
