version: "2.4"
services:
  clickhouse:
    image: "yandex/clickhouse-server"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9999:9000" # native interface
      - "8888:8123" # http interface
    mem_limit: 4G
    mem_reservation: 1G
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8123/"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./users.xml:/etc/clickhouse-server/users.xml
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      # - NUM_PARTITIONS=${NUM_PARTITIONS}
      - ITEMS_DIR=${ITEMS_DIR}
      - METADATA_DIR=${METADATA_DIR}
    ports:
      # UI
      - "4040:4040"
    mem_limit: 10G
    mem_reservation: 2G
    volumes:
      - ./data:/app/data
    depends_on:
      - clickhouse
    links:
      - clickhouse
    restart: on-failure
