version: "2.4"
services:
  clickhouse:
    image: "yandex/clickhouse-server"
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9999:9000" # native interface
      - "8888:8123" # http interface
    mem_limit: 4G
    mem_reservation: 1G
    healthcheck:
      # "clickhouse", "client", "-u ${CLICKHOUSE_USER}", "--password ${CLICKHOUSE_PASSWORD}", "-q 'SELECT 1'",
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      # use host volume to store data
      - ./clickhouse/database:/var/lib/clickhouse
      - ./clickhouse/server/config.d/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml
      - ./clickhouse/server/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse/init-db.d:/docker-entrypoint-initdb.d
  spark-job:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLICKHOUSE_SERVER=${CLICKHOUSE_SERVER}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      # - NUM_PARTITIONS=${NUM_PARTITIONS}
      - ITEMS_DIR=${ITEMS_DIR}
      - METADATA_DIR=${METADATA_DIR}
    ports:
      # UI
      - "4040:4040"
    mem_limit: 10G
    mem_reservation: 2G
    volumes:
      - ./data:/app/data
    depends_on:
      - clickhouse
    links:
      - clickhouse
    restart: on-failure
